version: '3.9'

services:

  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: "virtualstore"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - otus-pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    container_name: adminer_container
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  otus-pgdata:
